//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckedInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CheckedInvoice()
        {
            this.PickUpDelivery = new HashSet<PickUpDelivery>();
            this.Summary = new HashSet<Summary>();
        }
    
        public int checkedInvoiceID { get; set; }
        public int providerID { get; set; }
        public string cDeliveryReportNo { get; set; }
        public System.DateTime cDeliveryDate { get; set; }
        public int cNumberOfItems { get; set; }
        public string cCompany { get; set; }
        public string cOrderNumber { get; set; }
        public int cItemNumber { get; set; }
        public string cProductCode { get; set; }
        public string cProductName { get; set; }
        public string cSerialNo { get; set; }
        public int userID { get; set; }
    
        public virtual Provider Provider { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PickUpDelivery> PickUpDelivery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Summary> Summary { get; set; }
    }
}
