
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Warehouse
{

using System;
    using System.Collections.Generic;
    
public partial class Delivery
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Delivery()
    {

        this.Summary = new HashSet<Summary>();

    }


    public int deliveryID { get; set; }

    public int deliveryNoteID { get; set; }

    public bool @checked { get; set; }



    public virtual DeliveryNote DeliveryNote { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Summary> Summary { get; set; }

}

}
