//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryView
    {
        public string deliveryNumber { get; set; }
        public System.DateTime invoiceDate { get; set; }
        public int numberOfItems { get; set; }
        public string companyName { get; set; }
        public bool @checked { get; set; }
        public int deliveryID { get; set; }
    }
}
