//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncompatibleProductsView
    {
        public string cSerialNo { get; set; }
        public int deliveryNoteID { get; set; }
        public string forname { get; set; }
        public Nullable<System.DateTime> checkDate { get; set; }
    }
}
