//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.PickUpDelivery = new HashSet<PickUpDelivery>();
            this.Summary = new HashSet<Summary>();
            this.Supply = new HashSet<Supply>();
        }
    
        public int invoiceID { get; set; }
        public Nullable<int> providerID { get; set; }
        public string deliveryReportNo { get; set; }
        public Nullable<System.DateTime> deliveryDate { get; set; }
        public string company { get; set; }
        public string orderNumber { get; set; }
        public Nullable<int> itemNumber { get; set; }
        public string productCode { get; set; }
        public string productName { get; set; }
        public string serialNo { get; set; }
    
        public virtual Provider Provider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PickUpDelivery> PickUpDelivery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Summary> Summary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supply> Supply { get; set; }
    }
}
