//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class warehouseDatabaseEntities1 : DbContext
    {
        public warehouseDatabaseEntities1()
            : base("name=warehouseDatabaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CheckedInvoice> CheckedInvoice { get; set; }
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<PickUpDelivery> PickUpDelivery { get; set; }
        public virtual DbSet<Provider> Provider { get; set; }
        public virtual DbSet<Summary> Summary { get; set; }
        public virtual DbSet<Supply> Supply { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<ProviderInvoice> ProviderInvoice { get; set; }
    }
}
