//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class warehouseDatabaseEntities : DbContext
    {
        public warehouseDatabaseEntities()
            : base("name=warehouseDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<checkedInvoice> checkedInvoice { get; set; }
        public virtual DbSet<invoice> invoice { get; set; }
        public virtual DbSet<pickUpDelivery> pickUpDelivery { get; set; }
        public virtual DbSet<provider> provider { get; set; }
        public virtual DbSet<summary> summary { get; set; }
        public virtual DbSet<supply> supply { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
