
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Warehouse
{

using System;
    using System.Collections.Generic;
    
public partial class Product
{

    public int productID { get; set; }

    public int deliveryNoteID { get; set; }

    public string company { get; set; }

    public string orderNumber { get; set; }

    public int itemNumber { get; set; }

    public string productCode { get; set; }

    public string productName { get; set; }

    public string serialNo { get; set; }



    public virtual DeliveryNote DeliveryNote { get; set; }

}

}
