//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderInvoice
    {
        public string deliveryReportNo { get; set; }
        public Nullable<System.DateTime> deliveryDate { get; set; }
        public string companyName { get; set; }
        public Nullable<int> numberOfItems { get; set; }
        public System.DateTime addDate { get; set; }
        public bool deliveryStatus { get; set; }
    }
}
