
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Warehouse
{

using System;
    using System.Collections.Generic;
    
public partial class Summary
{

    public int summaryID { get; set; }

    public int deliveryNoteID { get; set; }

    public int deliveryID { get; set; }

    public int usersID { get; set; }

    public bool correct { get; set; }

    public bool closed { get; set; }

    public Nullable<System.DateTime> deliveryCloseDate { get; set; }



    public virtual Delivery Delivery { get; set; }

    public virtual DeliveryNote DeliveryNote { get; set; }

    public virtual Users Users { get; set; }

}

}
