//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class supply
    {
        public int supplyID { get; set; }
        public System.DateTime deliveryDate { get; set; }
        public int invoiceID { get; set; }
        public bool deliveryStatus { get; set; }
    
        public virtual invoice invoice { get; set; }
    }
}
