//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPermissions
    {
        public int userPermissionsID { get; set; }
        public int userID { get; set; }
        public int permissionsID { get; set; }
    
        public virtual Permissions Permissions { get; set; }
        public virtual Users Users { get; set; }
    }
}
